# Mod metadata
mod_id=futurearcanaheroes
mod_name=Future Arcana & Heroes
mod_version=0.1.0
mod_group_id=it.futurearcana
mod_authors=ThommyYT
mod_description=Future Arcana & Heroes Minecraft mod
mod_license=MIT

# Minecraft / Forge / mappings
minecraft_version=1.21.4
minecraft_version_range=1.21.4
forge_version=54.1.12
forge_version_range=[54.1.12,)
mapping_channel=official
mapping_version=1.21.4
loader_version_range=[1.0,)
